#
# gru_nosql-prd.tf
#

#---------------------------
# PRODUCTION
#---------------------------

#-------------------
# Table: estado_cidade
#-------------------
module "gru_table-motando_brasil_estados_cidades" {
    source = "./modules/nosql/table"
   
    providers = {
       oci = oci.gru
    }

    compartment_id = module.cmp_motando-nosql.id

    nosql_table = {
        name = "motando_estado_cidade",
        read_units = "1",
        write_units = "1",
        storage_gbs = "1",
        ddl_statement = <<EOS
           CREATE TABLE IF NOT EXISTS motando_estado_cidade (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
                estado STRING NOT NULL DEFAULT "NONE",
                sigla STRING NOT NULL DEFAULT "NONE",
                cidade ARRAY(RECORD(id INTEGER, cidade STRING)),
	       PRIMARY KEY(id))
        EOS
    }
}

#-------------------
# Table: moto
#-------------------
module "gru_table_motando_moto" {
    source = "./modules/nosql/table"
   
    providers = {
       oci = oci.gru
    }

    compartment_id = module.cmp_motando-nosql.id

    nosql_table = {
        name = "motando_moto",
        read_units = "1",
        write_units = "1",
        storage_gbs = "1",
        ddl_statement = <<EOS
           CREATE TABLE IF NOT EXISTS motando_moto (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),
                marca STRING NOT NULL DEFAULT "NONE",
                popular BOOLEAN NOT NULL DEFAULT FALSE,   
                modelo ARRAY(RECORD(id INTEGER, modelo STRING, estilo STRING, versao ARRAY(RECORD(id INTEGER, versao STRING)))),
	       PRIMARY KEY(id))
        EOS
    }
}

#-------------------
# Table: usuario
#-------------------
module "gru_table_motando_usuario" {
    source = "./modules/nosql/table"
   
    providers = {
       oci = oci.gru
    }

    compartment_id = module.cmp_motando-nosql.id

    nosql_table = {
        name = "motando_usuario",
        read_units = "1",
        write_units = "1",
        storage_gbs = "1",
        ddl_statement = <<EOS
           CREATE TABLE IF NOT EXISTS motando_usuario (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),                
                email STRING,
                email_confirmado BOOLEAN NOT NULL DEFAULT FALSE,
                nome STRING,
                senha STRING,                
                admin BOOLEAN NOT NULL DEFAULT FALSE,
                logista BOOLEAN NOT NULL DEFAULT FALSE,
                perfil_img_url STRING,
                banner_img_url STRING,
                telefone ARRAY(STRING),
                whatsapp ARRAY(STRING),
                cidade STRING,
                estado STRING,
                estado_sigla STRING,
                cep STRING,
                endereco STRING,             
                anuncio_id ARRAY(STRING),
                data_cadastro TIMESTAMP(0),
                data_modificacao TIMESTAMP(0),
	       PRIMARY KEY(id, email))
        EOS
    }
}

#-------------------
# Table: anuncio
#-------------------
module "gru_table_motando_anuncio" {
    source = "./modules/nosql/table"
   
    providers = {
       oci = oci.gru
    }

    compartment_id = module.cmp_motando-nosql.id

    nosql_table = {
        name = "motando_anuncio",
        read_units = "1",
        write_units = "1",
        storage_gbs = "1",
        ddl_statement = <<EOS
           CREATE TABLE IF NOT EXISTS motando_anuncio (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1 INCREMENT BY 1),               
                usuario_id INTEGER,
                anuncio JSON,
                valor NUMBER NOT NULL DEFAULT 0,
                data_cadastro TIMESTAMP(0),
                data_modificacao TIMESTAMP(0),
	       PRIMARY KEY(id))
        EOS
    }
}